const { venda, compra, sub, triangulo, mmInteger, senhaUser, mynewFunction } = require('./utils')

const rvenda = venda(500)
console.log(rvenda)
const rcompra = compra(800)
console.log(rcompra)
const rsub = sub(200-162)
console.log(rsub)
const rtriangulo = triangulo(5, 5, 5)
console.log(rtriangulo)
const rint = mmInteger(4, 6, 0)
console.log(rint)
const rsenha = senhaUser('adminadmin1234')
console.log(rsenha)
const rfunc = mynewFunction(4, 6)
console.log(rfunc)